language: java

jdk:
  - openjdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'

jobs:
  include:
    - stage: compile
      script:
        - ./gradlew check --stacktrace
        - ./gradlew assemble --stacktrace
    - stage: deploy
      if: branch = master
      script:
        - ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET

notifications:
  email: true
